#ifndef _OMNISCIENTSCENECONTROL_H_
#define _OMNISCIENTSCENECONTROL_H_

enum
{
    OMNISCIENTSCENECONTROL_BACKGROUND_VISIBILITY = 1000001,
    OMNISCIENTSCENECONTROL_SAFE_FRAME_VISIBILITY = 1000002,
    OMNISCIENTSCENECONTROL_VIEWPORT_GRID_VISIBILITY = 1000003,

    OMNISCIENTSCENECONTROL_BACKGROUND_LINK = 1000004,

    OMNISCIENTSCENECONTROL_VIEW_THROUGH_CAMERA = 2000,
    OMNISCIENTSCENECONTROL_ALWAYS = 2001,
    OMNISCIENTSCENECONTROL_NEVER = 2002,
    OMNISCIENTSCENECONTROL_ONLY_NOT_THROUGH_CAM = 2003
};

#endif
