#ifndef _TSAFEFRAMETAG_H_
#define _TSAFEFRAMETAG_H_

enum
{
    USERDATA_BACKGROUND_VISIBILITY = 1000,
    USERDATA_SAFE_FRAME_VISIBILITY = 1001,
    USERDATA_VIEWPORT_GRID_VISIBILITY = 1002
};

#endif
